# Generated by Django 4.0.5 on 2022-06-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='Noteid',
            new_name='noteid',
        ),
    ]
