# Generated by Django 4.0.5 on 2022-06-17 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_rename_noteid_tags_noteid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
